### ISSUE TITLE
[Feature Request] Write to image option

### ISSUE THREAD

**Issue by trholding** [vampirefrog/fathuman#7]
Hi @vampirefrog I started X68000 development for fun and created my first helloworld.X, I have tried to create a floppy image like this:

```
dd if=/dev/zero of=hello.dim bs=512 count=2468
mkfs.vfat -F 12 -n "HELLO_X68K" hello.dim
mcopy -i hello.dim  helloworld.X ::/
```
But this isn't readable. I get a black screen with some white japanese text.

So I put this on second floppy drive and booted human68k in first floppy and tried to access b: and it seems not readable.

Do you have any hints or can you add the option to write images / bootable images.

Any hints would be appreciated. 

Cheers!
- Vulcan

**Comment by vampirefrog** [comment]
See comment on #1.

**Comment by vampirefrog** [comment]
Looks like github mobile doesn't have "close as duplicate".

**Comment by vampirefrog** [comment]
Anyway it's not a normal FAT filesystem, it has some differences. You might want to just use an emulator that can open folders as floppies, or get an english boot floppy or learn japanese or ask on the [x68000 forum](https://nfggames.com/forum2/index.php?board=14.0)

**Comment by trholding** [comment]
Thanks, closing this, as it is a duplicate
